In [1]:
import numpy as np
import sys
import itertools as itertools
import PSpincalc as sp

#    Q        Rotation Quaternions                Q - [q1,q2,q3,q4] (Nx4)
#    EV       Euler Vector and rotation angle (degrees)    EV - [m1,m2,m3,MU] (Nx4)
#    DCM      Orthogonal DCM Rotation Matrix            DCM - 3x3xN
#    EA    Euler angles (12 possible sets) (degrees)        EA - [psi,theta,phi] (Nx3)

# DCM2EA    DCM2EV    DCM2Q   EA2EA
# EA2DCM    EA2EV    EA2Q    Q2GL
# EV2DCM    EV2EA    EV2Q*
# Q2DCM*        Q2EA    Q2EV*

Q1 = np.array([-0.1677489, -0.7369231, -0.3682588, 0.5414703])
Q2 = (-0.8735598,  0.1145235, -0.2093062, 0.4242270)
Q3 = [0.426681700, -0.20287610,  0.43515810, -0.76643420]
Q4 = np.array([[-0.1677489, -0.7369231, -0.3682588, 0.5414703],
[-0.8735598,  0.1145235, -0.2093062, 0.4242270],
[0.426681700, -0.20287610,  0.43515810, -0.76643420]])

EV1 = np.array([[-0.1995301, -0.8765382, -0.4380279, 114.4324]])
EV2 = np.array([-9.646669e-001, 1.264676e-001, -2.311356e-001, 1.297965e+002])
EV3 = np.array([6.642793e-001, -3.158476e-001, 6.774757e-001, 2.800695e+002])
EV4 = np.array([[-1.995301e-001, -8.765382e-001, -4.380280e-001, 1.144324e+002],
[-9.646669e-001, 1.264676e-001, -2.311356e-001, 1.297965e+002],
[6.642793e-001, -3.158476e-001, 6.774757e-001, 2.800695e+002]])

DCM1 = np.array([[-0.3573404, -0.1515663, 0.9215940], [0.6460385, 0.6724915, 0.3610947], [-0.6744939, 0.7244189, -0.1423907]])
DCM2 = np.array([[0.88615060, -0.3776729,  0.2685150],[-0.02249957, -0.6138316, -0.7891163],[0.46285090,  0.6932344, -0.5524447]])
DCM3 = np.array([[0.5389574, -0.8401672,  0.06036564],[0.4939131, 0.2571603, -0.83061330],[0.6823304, 0.4774806, 0.55356800]])
DCM4 = np.array([[[-0.3573404, -0.1515663, 0.9215940], [0.6460385, 0.6724915, 0.3610947], [-0.6744939, 0.7244189, -0.1423907]],
[[0.88615060, -0.3776729,  0.2685150],[-0.02249957, -0.6138316, -0.7891163],[0.46285090,  0.6932344, -0.5524447]],
[[0.5389574, -0.8401672,  0.06036564],[0.4939131, 0.2571603, -0.83061330],[0.6823304, 0.4774806, 0.55356800]]])

EAxyx = [[0.3734309, 1.427920, 2.3205212],[-1.2428130, 0.985502, 0.9821003],[-1.4982479, 2.157439, 0.6105777]]
EAxyz = [[2.07603606, -0.7402790, -1.376712],[-0.02538478,  0.4812086, -0.897943], [0.74181498,  0.7509456, -2.429857]]
EAxzy = [[-2.9199163, -0.8101911, -1.3627437],[-0.5515727, -0.7659671,  0.6973821],[-1.8678238, -0.4977850,  2.2523838]]
EAyzx = [[1.4175036,  0.3694416,  2.3762543],[0.4524244, -0.9093689, -0.0366379],[3.0329736, -0.9802081,  2.0508342]]
EAyxz = [[-2.0579912,  0.70238301,  2.6488233], [0.4813408, -0.02250147, -0.9096943], [0.9022582,  0.51658433, -1.8710396]]
EAzxy = [[-2.3190385, -0.1521527, 1.9406908],[-0.8460724, -0.3872818, 0.2942186],[-2.0648275, -0.9975913, 0.1115396]]
EAzyx = [[1.1951869, 1.17216717, -2.7404413],[-0.9600165, 0.27185113, -0.4028824],[-2.1586537, 0.06040236, -1.0004280]]
EAxzx = [[-1.197365, 1.427920, -2.391868],[-2.813609, 0.985502,  2.552897],[-3.069044, 2.157439,  2.181374]]
EAyxy = [[1.777046, 2.3083664,  0.5096786],[2.069637, 0.9098912, -1.5993010],[2.624796, 1.8308788, -1.0343298]]
EAyzy = [[-2.935343, 2.3083664, -1.061118],[-2.642752, 0.9098912,  3.113088],[-2.087593, 1.8308788, -2.605126]]
EAzxz = [[-0.8069433, 1.9362151, -1.733798], [1.6193689, 0.4818253, -2.523541], [0.9442344, 1.0015975, -3.069866]]
EAzyz = [[-2.3777396, 1.9362151, -0.1630019], [0.0485726, 0.4818253, -0.9527442],[-0.6265619, 1.0015975, -1.4990700]]
EAall = np.vstack([EAxyx,EAxyz,EAxzy,EAyzx,EAyxz,EAzxy,EAzyx,EAxzx,EAyxy,EAyzy,EAzxz,EAzyz])
EAvct = ["xyx","xyz","xzy","yzx","yxz","zxy","zyx","xzx","yxy","yzy","zxz","zyz"]

In [2]:
# Example: Qnorm and Qnormalize
print('Qnorm and Qnormalize')
print(sp.Qnormalize(Q1))
print(sp.Qnormalize(Q4))
print(sp.Qnorm(Q1))
print(sp.Qnorm(Q4))

Qnorm and Qnormalize
[-0.1677489  -0.73692311 -0.3682588   0.54147031]
[[-0.1677489  -0.73692311 -0.3682588   0.54147031]
 [-0.8735598   0.1145235  -0.2093062   0.424227  ]
 [ 0.42668171 -0.20287611  0.43515811 -0.76643422]]
[1.]
[0.99999999 0.99999999 0.99999997]


In [3]:
# Example: Q2EV and EV2Q
print('Q2EV')
print(sp.Q2EV(Q1))
print(sp.Q2EV(Q2))
print(sp.Q2EV(Q3))
print(sp.Q2EV(Q4))
print('EV2Q')
print(sp.EV2Q(EV1,1e-7))
print(sp.EV2Q(EV2,1e-7))
print(sp.EV2Q(EV3,1e-7))
print(sp.EV2Q(EV4,1e-7))

Q2EV
[[0.19953008 0.87653823 0.43802795 4.28596264]]
[[ 0.96466692 -0.12646762  0.2311356   4.01780885]]
[[-0.66427924  0.31584758 -0.67747572  1.39505018]]
[[ 0.19953008  0.87653822  0.43802795  4.28596264]
 [ 0.96466692 -0.12646762  0.2311356   4.01780885]
 [-0.66427924  0.31584758 -0.67747572  1.39505018]]
EV2Q
(At least one of the) input Euler vector(s) is not a unit vector

[[ 0.78535172 -0.12351907 -0.54262081 -0.27116109]]
(At least one of the) input Euler vector(s) is not a unit vector

[[-0.47556008 -0.84860131  0.11125143 -0.20332611]]
(At least one of the) input Euler vector(s) is not a unit vector

[[-0.23175062  0.64619445 -0.30724872  0.65903158]]
(At least one of the) input Euler vector(s) is not a unit vector

[[ 0.78535172 -0.12351907 -0.54262081 -0.27116115]
 [-0.47556008 -0.84860131  0.11125143 -0.20332611]
 [-0.23175062  0.64619445 -0.30724872  0.65903158]]


In [4]:
# Example: DCM2Q and Q2DCM
print('DCM2Q')
print(sp.DCM2Q(DCM1))
print(sp.DCM2Q(DCM2))
print(sp.DCM2Q(DCM3))
print(sp.DCM2Q(DCM4))
print('Q2DCM')
print(sp.Q2DCM(Q1))
print(sp.Q2DCM(Q2))
print(sp.Q2DCM(Q3))
print(sp.Q2DCM(Q4))

DCM2Q
[[-0.54147031  0.16774892  0.7369231   0.36825878]]
[[-0.42422702  0.8735598  -0.11452349  0.20930619]]
[[ 0.76643423 -0.42668172  0.2028761  -0.43515812]]
[[-0.54147031  0.16774892  0.7369231   0.36825878]
 [-0.42422702  0.8735598  -0.11452349  0.20930619]
 [ 0.76643423 -0.42668172  0.2028761  -0.43515812]]
Q2DCM
[[ 0.14239072  0.36109475 -0.92159398]
 [ 0.72441894 -0.67249152 -0.15156633]
 [-0.67449394 -0.6460385  -0.35734043]]
[[ 0.55244473 -0.78911627 -0.26851505]
 [ 0.69323436  0.61383164 -0.37767294]
 [ 0.46285089  0.02249957  0.88615056]]
[[-0.553568   -0.8306133  -0.06036564]
 [ 0.47748057 -0.25716027 -0.84016719]
 [ 0.6823304  -0.49391309  0.5389574 ]]
[[[ 0.14239072  0.36109475 -0.92159398]
  [ 0.72441894 -0.67249152 -0.15156633]
  [-0.67449394 -0.6460385  -0.35734043]]

 [[ 0.55244473 -0.78911627 -0.26851505]
  [ 0.69323436  0.61383164 -0.37767294]
  [ 0.46285089  0.02249957  0.88615056]]

 [[-0.553568   -0.8306133  -0.06036564]
  [ 0.47748057 -0.25716027 -0.84016719]


In [5]:
# Example: Q2EA and EA2Q
print('Q2EA')
for EAv in EAvct:
    print (sp.Q2EA(Q1,EAv))
    print (sp.Q2EA(Q2,EAv))
    print (sp.Q2EA(Q3,EAv))
for EAv in EAvct:
    print (sp.Q2EA(Q4,EAv))
print('EA2Q')
n = 0
for EAv in list(itertools.chain(*zip(EAvct,EAvct,EAvct))):
    print (sp.EA2Q(EAall[n,:],EAv))
    n = n+1
n = 0
for EAv in EAvct:
    print (sp.EA2Q(EAall[range(n,1+(n+2)),:],EAv))
    n = n+3

Q2EA
[[0.37343087 1.42792    2.3205212 ]]
[[-1.24281303  0.98550202  0.98210032]]
[[-1.4982479   2.15743878  0.61057771]]
[[ 2.07603606 -0.74027903 -1.37671205]]
[[-0.02538478  0.48120863 -0.89794296]]
[[ 0.74181498  0.75094563 -2.42985714]]
[[-2.91991628 -0.81019113 -1.36274366]]
[[-0.55157273 -0.76596714  0.69738206]]
[[-1.86782379 -0.49778502  2.25238376]]
[[1.41750361 0.36944158 2.37625431]]
[[ 0.45242441 -0.90936893 -0.0366379 ]]
[[ 3.03297357 -0.98020807  2.05083416]]
[[-2.05799127  0.70238303  2.64882332]]
[[ 0.48134085 -0.02250147 -0.90969431]]
[[ 0.90225816  0.51658433 -1.87103965]]
[[-2.31903855 -0.15215272  1.94069075]]
[[-0.84607242 -0.38728181  0.29421862]]
[[-2.06482755 -0.99759134  0.1115396 ]]
[[ 1.19518686  1.17216723 -2.74044126]]
[[-0.9600165   0.27185113 -0.40288239]]
[[-2.15865372  0.06040236 -1.00042803]]
[[-1.19736546  1.42792    -2.39186778]]
[[-2.81360936  0.98550202  2.55289665]]
[[-3.06904422  2.15743878  2.18137403]]
[[1.77704584 2.30836643 0.50967864]]
[[ 2

In [6]:
# Example: DCM2EV and EV2DCM
print('DCM2EV')
print(sp.DCM2EV(DCM1))
print(sp.DCM2EV(DCM2))
print(sp.DCM2EV(DCM3))
print(sp.DCM2EV(DCM4))
print('EV2DCM')
print(sp.EV2DCM(EV1,1e-7))
print(sp.EV2DCM(EV2,1e-7))
print(sp.EV2DCM(EV3,1e-7))
print(sp.EV2DCM(EV4,1e-7))

DCM2EV
[[ 0.5823994  -0.18042885 -0.79262623  3.89586364]]
[[ 0.43383644 -0.89334731  0.11711763  3.56332342]]
[[-0.85125871  0.47390437 -0.22532925  2.24116489]]
[[ 0.5823994  -0.18042885 -0.79262623  3.89586364]
 [ 0.43383644 -0.89334731  0.11711763  3.56332342]
 [-0.85125871  0.47390437 -0.22532925  2.24116489]]
EV2DCM
(At least one of the) input Euler vector(s) is not a unit vector

[[ 0.26406862 -0.29186563  0.91928353]
 [ 0.55996171  0.8224294   0.10026347]
 [-0.78530927  0.48828714  0.38061138]]
(At least one of the) input Euler vector(s) is not a unit vector

[[ 0.89256322  0.00457135  0.45089911]
 [-0.3822038  -0.52293145  0.7618812 ]
 [ 0.23927215 -0.85236248 -0.46500219]]
(At least one of the) input Euler vector(s) is not a unit vector

[[-0.05744878 -0.70254678  0.70931492]
 [-0.09162288 -0.70377975 -0.70448514]
 [ 0.99413525 -0.10546129 -0.02393807]]
(At least one of the) input Euler vector(s) is not a unit vector

[[[ 0.26406858 -0.29186572  0.91928352]
  [ 0.55996179  0.

In [7]:
# Example: DCM2EA and EA2DCM
print('DCM2EA')
for EAv in EAvct:
    print(sp.DCM2EA(DCM1,EAv))
    print(sp.DCM2EA(DCM2,EAv))
    print(sp.DCM2EA(DCM3,EAv))
for EAv in EAvct:
    print(sp.DCM2EA(DCM4,EAv))
print('EA2DCM')
print(sp.EA2DCM(EAxyx,'xyx',1e-7))
print(sp.EA2DCM(EAxyz,'xyz',1e-7))
print(sp.EA2DCM(EAxzy,'xzy',1e-7))
print(sp.EA2DCM(EAyzx,'yzx',1e-7))
print(sp.EA2DCM(EAyxz,'yxz',1e-7))
print(sp.EA2DCM(EAzxy,'zxy',1e-7))
print(sp.EA2DCM(EAzyx,'zyx',1e-7))
print(sp.EA2DCM(EAxzx,'xzx',1e-7))
print(sp.EA2DCM(EAyxy,'yxy',1e-7))
print(sp.EA2DCM(EAyzy,'yzy',1e-7))
print(sp.EA2DCM(EAzxz,'zxz',1e-7))
print(sp.EA2DCM(EAzyz,'zyz',1e-7))

DCM2EA
[[-2.97859077  1.93621503  2.37773962]]
[[-2.18884844  0.48182525 -0.04857256]]
[[-1.64252264  1.00159744  0.62656191]]
[[-1.76488062 -0.74027901 -2.07603602]]
[[-2.24364965  0.48120861  0.02538476]]
[[-0.71173553  0.75094569 -0.74181497]]
[[ 0.49276926 -0.70238302 -2.05799123]]
[[-2.23189831  0.02250145  0.48134083]]
[[-1.27055302 -0.51658437  0.90225821]]
[[-1.94069072 -0.15215268 -0.82255409]]
[[-0.2942186  -0.38728179 -2.29552018]]
[[-0.11153961 -0.99759145 -1.07676513]]
[[-1.77884896 -0.81019108 -0.22167632]]
[[ 2.4442106  -0.7659672  -2.59001993]]
[[ 0.88920891 -0.49778507 -1.27376888]]
[[-0.76533834  0.36944152 -1.72408905]]
[[ 3.10495479 -0.90936899 -2.68916825]]
[[-1.0907585  -0.98020819 -0.1086191 ]]
[[-2.74044132 -1.1721672   1.94640586]]
[[-0.40288236 -0.27185112 -2.18157612]]
[[-1.00042803 -0.06040237 -0.98293893]]
[[ 1.73379821  1.93621503 -2.33464936]]
[[2.52354055 0.48182525 1.52222377]]
[[3.06986634 1.00159744 2.19735824]]
[[ 1.06111775  0.83322623 -2.93534318]]

In [8]:
# Example: EA2EV an EV2EA
print('EA2EV')
print(sp.EA2EV(EAxyx,'xyx',1e-7))
print(sp.EA2EV(EAxyz,'xyz',1e-7))
print(sp.EA2EV(EAxzy,'xzy',1e-7))
print(sp.EA2EV(EAyzx,'yzx',1e-7))
print(sp.EA2EV(EAyxz,'yxz',1e-7))
print(sp.EA2EV(EAzxy,'zxy',1e-7))
print(sp.EA2EV(EAzyx,'zyx',1e-7))
print(sp.EA2EV(EAxzx,'xzx',1e-7))
print(sp.EA2EV(EAyxy,'yxy',1e-7))
print(sp.EA2EV(EAyzy,'yzy',1e-7))
print(sp.EA2EV(EAzxz,'zxz',1e-7))
print(sp.EA2EV(EAzyz,'zyz',1e-7))
print('EV2EA')
for EAv in EAvct:
    print (sp.EV2EA(EV1,EAv,1e-7))
    print (sp.EV2EA(EV2,EAv,1e-7))
    print (sp.EV2EA(EV3,EAv,1e-7))
for EAv in EAvct:
    print (sp.EV2EA(EV4,EAv,1e-7))

EA2EV
[[-0.19953006 -0.87653822 -0.43802796  1.99722268]
 [-0.96466692  0.12646762 -0.23113561  2.26537648]
 [-0.66427919  0.31584756 -0.67747582  1.39505007]]
[[-0.1995301  -0.87653823 -0.43802793  1.9972227 ]
 [-0.96466693  0.12646762 -0.23113558  2.26537641]
 [-0.66427931  0.31584748 -0.67747573  1.39505022]]
[[ 0.19953009  0.87653823  0.43802794  4.28596269]
 [-0.96466692  0.12646761 -0.23113563  2.2653765 ]
 [-0.66427922  0.31584759 -0.67747577  1.39505017]]
[[-0.19953008 -0.87653822 -0.43802796  1.99722269]
 [-0.96466693  0.12646762 -0.23113559  2.2653765 ]
 [-0.66427924  0.31584758 -0.67747576  1.39505013]]
[[ 0.19953005  0.87653822  0.43802797  4.2859627 ]
 [-0.96466693  0.12646761 -0.23113557  2.26537646]
 [-0.66427929  0.31584757 -0.67747571  1.39505021]]
[[-0.19953009 -0.87653822 -0.43802796  1.99722273]
 [-0.96466693  0.12646762 -0.23113559  2.26537648]
 [-0.66427933  0.31584756 -0.67747567  1.39505014]]
[[ 0.19953008  0.87653821  0.43802798  4.28596257]
 [-0.96466692  0.12

In [9]:
# Example: Q2GL
print('Q2GL')
print(sp.Q2GL(Q1))
print(sp.Q2GL(Q2))
print(sp.Q2GL(Q3))
print(sp.Q2GL(Q4))

Q2GL
[[-0.67249152 -0.15156633 -0.72441894  0.        ]
 [ 0.6460385   0.35734043 -0.67449394  0.        ]
 [ 0.36109475 -0.92159398 -0.14239072  0.        ]
 [ 0.          0.          0.          1.        ]]
[[ 0.61383164 -0.37767294 -0.69323436  0.        ]
 [-0.02249957 -0.88615056  0.46285089  0.        ]
 [-0.78911627 -0.26851505 -0.55244473  0.        ]
 [ 0.          0.          0.          1.        ]]
[[-0.25716027 -0.84016719 -0.47748057  0.        ]
 [ 0.49391309 -0.5389574   0.6823304   0.        ]
 [-0.8306133  -0.06036564  0.553568    0.        ]
 [ 0.          0.          0.          1.        ]]
[[-0.67249152 -0.15156633 -0.72441894  0.        ]
 [ 0.6460385   0.35734043 -0.67449394  0.        ]
 [ 0.36109475 -0.92159398 -0.14239072  0.        ]
 [ 0.          0.          0.          1.        ]
 [ 0.61383164 -0.37767294 -0.69323436  0.        ]
 [-0.02249957 -0.88615056  0.46285089  0.        ]
 [-0.78911627 -0.26851505 -0.55244473  0.        ]
 [ 0.          0.      

In [10]:
# Example: EA2EA
# xyx to ...
print('EA2EA')
print(sp.EA2EA(EAxyx,"xyx","xyz"))
print(EAxyz)
print(sp.EA2EA(EAxyx,'xyx','xzy'))
print(EAxzy)
print(sp.EA2EA(EAxyx,'xyx','yzx'))
print(EAyzx)
print(sp.EA2EA(EAxyx,'xyx','yxz'))
print(EAyxz)
print(sp.EA2EA(EAxyx,'xyx','zxy'))
print(EAzxy)
print(sp.EA2EA(EAxyx,'xyx','zyx'))
print(EAzyx)
print(sp.EA2EA(EAxyx,'xyx','xzx'))
print(EAxzx)
print(sp.EA2EA(EAxyx,'xyx','yxy'))
print(EAyxy)
print(sp.EA2EA(EAxyx,'xyx','yzy'))
print(EAyzy)
print(sp.EA2EA(EAxyx,'xyx','zxz'))
print(EAzxz)
print(sp.EA2EA(EAxyx,'xyx','zyz'))
print(EAzyz)

EA2EA
[[ 2.07603609 -0.74027903 -1.37671206]
 [-0.02538477  0.48120864 -0.89794293]
 [ 0.74181511  0.75094557 -2.42985733]]
[[2.07603606, -0.740279, -1.376712], [-0.02538478, 0.4812086, -0.897943], [0.74181498, 0.7509456, -2.429857]]
[[-2.91991624 -0.81019113 -1.36274366]
 [-0.5515727  -0.76596712  0.69738206]
 [-1.86782388 -0.49778498  2.25238394]]
[[-2.9199163, -0.8101911, -1.3627437], [-0.5515727, -0.7659671, 0.6973821], [-1.8678238, -0.497785, 2.2523838]]
[[ 1.41750362  0.36944161  2.37625431]
 [ 0.45242444 -0.90936891 -0.03663788]
 [ 3.03297362 -0.98020798  2.0508342 ]]
[[1.4175036, 0.3694416, 2.3762543], [0.4524244, -0.9093689, -0.0366379], [3.0329736, -0.9802081, 2.0508342]]
[[-2.0579913   0.70238302  2.64882328]
 [ 0.48134086 -0.02250146 -0.90969428]
 [ 0.90225817  0.51658451 -1.87103978]]
[[-2.0579912, 0.70238301, 2.6488233], [0.4813408, -0.02250147, -0.9096943], [0.9022582, 0.51658433, -1.8710396]]
[[-2.31903854 -0.15215274  1.94069078]
 [-0.84607239 -0.38728181  0.29421864]
